### ISSUE TITLE
No forms-ext extensions at all on IE, regardless of version and settings

### ISSUE THREAD

**Issue by tdd** [aFarkas/webshim#409]
Hi all,

SO and Google don't seem to help with this… I've built a nice forms utility belt on top of Webshims' forms and forms-ext polyfills, but on any IE I qualify against (9-11), forms-ext fields such as date, time, datetime-local, range and color are not polyfilled at all. I get IE's native range field on 10+, and basic texts everywhere else.

Not only that, but a valid value in a color field yields an invalid iVal when left alone and just tabbing through.

I tried various combos of `replaceUI`, `extendNative` and `enhanceAuto`, to no avail. My base settings are as follows:

``` js
webshim.setOptions({
  basePath: '/shims/',
  forms: {
    addValidators: true,
    iVal: {
      handleBubble: 'hide',
      errorMessageClass: 'help-block',
      successWrapperClass: 'has-success',
      errorWrapperClass: 'has-error',
      fieldWrapper: '.form-group'
    },
    lazyCustomMessages: true
  },
  'forms-ext': {
    range: {
      classes: "show-valuetooltip"
    },
    replaceUI: 'auto',
    types: 'datetime-local range date time number color',
    widgets: {
      classes: "show-yearbtns show-selectnav",
      minView: 2,
      startView: 2
    }
  }
});
webshim.polyfill('forms forms-ext');
```

Defining `extendNative: true` or `replaceUI: true` or even `enhanceAuto: true` doesn't seem to help at all…

Any pointers? I absolutely need IE9+ working with this, and judging by the issue tracker and docs it absolutely should!

Thanks!

**Comment by aggieben** [comment]
I seem to be having a similar issue in IE11.  I'm initializing like this:

```
<script src="/Scripts/jquery-2.1.4.js"></script>
<script src="/Scripts/modernizr-2.8.3.js"></script>
<script src="/Scripts/polyfiller.js"></script>

<script type="text/javascript">
    webshims.setOptions({
        "debug": true,
        "forms-ext": { replaceUI: true },
    })
    webshims.polyfill("forms forms-ext")
</script>
```

I can't really tell that much of anything is happening, except that in the F12 tools I can see the shim scripts being loaded:

![image](https://cloud.githubusercontent.com/assets/1321/7760164/4524e820-ffde-11e4-826a-5d54912b0a70.png)

Though I set `debug: true` in the options, nothing gets written to the console.  Have I missed something obvious?

After reading this issue, I did check to see that my X-UA-Compatibility meta tag was setting the IE rendering engine to edge, so that shouldn't be the problem.
