### ISSUE TITLE
Using addEventListener and setCustomValidity does not trigger the polyfill

### ISSUE THREAD

**Issue by shefik** [aFarkas/webshim#498]
When using webshim with the "forms" polyfill (in Safari on Mac), the constraint does not work when a JavaScript file contains code to "addEventListener" and "setCustomValidity". The form is able to be submitted without validation.

**Comment by shefik** [comment]
For example, this type of snippet code works in other browsers, except for Safari (which relies on the polyfill):

```
        $('input[data-match]').each(function() {
            var $this = $(this);
            var match = $this.data('match');

            /**
             * Check if fields match.
             */
            var e1 = $this[0];
            var e2 = document.getElementById(match.substr(1));
            var checkMatch = function() {
                if (e1.value != e2.value) {
                    e2.setCustomValidity($this.data('match-error-message'));
                } else {
                    e2.setCustomValidity('');
                }
            };

            e1.addEventListener('change', checkMatch, false);
            e2.addEventListener('keyup', checkMatch, false);
            e2.addEventListener('paste', checkMatch, false);
        });
```

**Comment by aFarkas** [comment]
This is by design and [explained here](http://afarkas.github.io/webshim/demos/index.html#Guide-dom-abstractions). Please read carefully.

The technical problem here is that if Safari implements a feature, they make it never configurable. This means, if they have an implementation, but this implementation is only partial, you can't fix it using the native API and must write some kind of minimal abstraction layer.

Here is a test for you:

```js
Object.getOwnPropertyDescriptor(document.createElement('input'), 'validity') || Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'validity');
```

**Comment by aFarkas** [comment]
Please blame apple. The most annoying browser on earth.

**Comment by shefik** [comment]
@aFarkas Thanks. It worked, based on the docs you provided.
