### ISSUE TITLE
Chrome Version 43.0.2357.81 m (64-bit)  

### ISSUE THREAD

**Issue by maxbar3** [aFarkas/webshim#527]
Hi aFarkas,
 
I am having an issue with my error message text not showing up in Chrome specifically Version 43.  It works just fine in other versions but not 43. 
My input box  looks like the follows. 
<input id="idfirstname" type="text" name="firstname" data-errormessage="{"valueMissing":"Can you just give us a little something? This field is required so you kind of have to!"}" required="required" class="form-ui-invalid">

The validation occurs just fine. The data-errormessage attribute doesn't get picked up.  It works in all other browsers and other chrome versions.  Do you know of any issue with Chrome 43 ? 

thank you in advance. 

p.s  this is how i am setting up webshims

// begin webshims
		$.webshims.setOptions({
			loadStyles : false,
			waitReady : false,
			forms : {
				replaceValidationUI : true,
                customMessages: true,
                overrideMessages: true
			}
		});
        
		$.webshims.polyfill('forms forms-ext');

Also if i fire a validation error message from  JS like $.webshims.validityAlert.showFor($idemailaddress, $idemailaddress.data('errormessage').api);  it works just fine.

**Comment by oxeno** [comment]
Hi, we are having the same issue, for us it's only for fields that are inside fieldsets. The Chrome version is the same (43.0.2357).

That's part of our config

```
$.webshims.setOptions("forms", { 
customMessages: true, 
replaceValidationUI: true, 
addValidators: true 
});

we don't have this problem in any other browser.

**Comment by aFarkas** [comment]
Yeah, reason for this is that the fieldset element itself now also fires an invalid event, if there are invalid elements inside. Additionally also the ``:invalid`` selector also applies to ``fieldset`` elements. The same is also true for ``form`` elements.

Which is basically a great feature. For example you can do this:

```css
form:invalid [type="submit"] { cursor: not-allowed;}
```

But I really don't understand, why the semantics of an existing event and an selector is extended, instead of inventing a new one. (This really hurts web compat).

Please update with my fix.

**Comment by maxbar3** [comment]
thank you aFarkas that worked your the man.
